version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: yarn start
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/app/src
    # ports:
    #   - '3000:3000'
  backend:
    build:
      context: ./backend
    container_name: backend
    command: start
    volumes:
      - ./backend/src:/usr/app/src
    # ports:
    #   - '3001:3001'
  nginx:
    container_name: reverse_proxy
    image: nginx:1.18.0-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
